### PR TITLE
Remove loop parameter

### LINKED ISSUE #9: Compatibility issue with Python 3.10
Hi,

thanks for this great library!

There is a small issue when using Python 3.10, use of a deprecated function argument makes the code stop working. This was noticed because it breaks a smart meter integration in Home Assistant that relies on pysml. Would be great if you can fix it!

Relevant traceback:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/edl21/sensor.py", line 264, in async_setup_platform
    await hass.data[DOMAIN].connect()
  File "/usr/src/homeassistant/homeassistant/components/edl21/sensor.py", line 291, in connect
    await self._proto.connect(self._hass.loop)
  File "/usr/local/lib/python3.10/site-packages/sml/asyncio.py", line 132, in connect
    self._lock = asyncio.Lock(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

### PR DESCRIPTION
**Pull request by DavidMStraub**
Fixes #9 - at least it should, I haven't been able to test it.

### CODE REVIEW

**Comment by mtdcr** [comment]
Hi David! Thanks for your PR! It looks good, but unfortunately I can't test it with Python 3.10 either.

I can merge this, but before this update will be included in Home Assistant, someone will probably need to test it. What do you think? Will you be able to test it?

**Comment by DavidMStraub** [comment]
I'm trying to override the core HA integration with a custom one fetching the library from my PR branch.

**Comment by DavidMStraub** [comment]
Yes, my sensors are back! So I can confirm this works on Python 3.10 (using HA OS).

**Comment by mtdcr** [comment]
Thanks again! I've uploaded 0.0.8 to pypi. Are you going to submit a PR to Home Assistant?

**Comment by DavidMStraub** [comment]
I will, please don't forget to push a tag or make a release on Github as well.

**Comment by mtdcr** [comment]
> please don't forget to push a tag or make a release on Github as well.

Of course I forgot. :-)

**Pull request merged**
